version: "3.7"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - hhrr-guacamole:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - FLASK_ENV=docker
    ports:
      5000:5000
    volumes:
      - .:/app
    entrypoint:
      - /app/scripts/docker_script.sh

volumes:
  guacamole:
    name: guacamole
